### ISSUE TITLE
Rancher will not run on Java 8

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/cattle#110]
Running on Java 8 yields the following exception on startup

```
Caused by: java.beans.IntrospectionException: type mismatch between read and write methods
	at org.springframework.beans.PropertyDescriptorUtils.findPropertyType(ExtendedBeanInfo.java:512)
	at org.springframework.beans.SimplePropertyDescriptor.<init>(ExtendedBeanInfo.java:257)
	at org.springframework.beans.SimplePropertyDescriptor.<init>(ExtendedBeanInfo.java:249)
	at org.springframework.beans.ExtendedBeanInfo.<init>(ExtendedBeanInfo.java:97)
	at org.springframework.beans.ExtendedBeanInfoFactory.getBeanInfo(ExtendedBeanInfoFactory.java:44)
	at org.springframework.beans.CachedIntrospectionResults.<init>(CachedIntrospectionResults.java:233)
	... 89 more
```

**Comment by ibuildthecloud** [comment]
This is due to a mismatch in the getter and setter of freemarker.core.Configurable.setSettings(Properties) and freemarker.core.Configurable.getSettings()

Apparently Java <= 7 did not care about this mismatch, but Java 8 does now.

FYI, @sidharthamani
